# -*- coding: utf-8 -*-
"""test_MartinRuiz

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Dd80grwjHwqhYW5e4o6m7TjE8ZHfC_Bb
"""

# Test code defined as a string
test_code = """
import unittest
import pandas as pd
from MartinRuiz import get_top20EUR, fetch_top_coins, date_unix

class TestKrakenAPI(unittest.TestCase):

    def test_get_top20EUR(self):
        result = get_top20EUR()
        self.assertIsInstance(result, pd.DataFrame)
        self.assertEqual(len(result), 20)
        self.assertIn('Coin', result.columns)
        self.assertIn('Price (EUR)', result.columns)

    def test_date_unix(self):
        date_str = "2023-01-01"
        result = date_unix(date_str)
        self.assertIsInstance(result, int)

    def test_fetch_top_coins(self):
        since_date = date_unix("2023-01-01")
        kraken_1440, kraken_60 = fetch_top_coins(since_date)
        self.assertIsInstance(kraken_1440, pd.DataFrame)
        self.assertIsInstance(kraken_60, pd.DataFrame)

if __name__ == '__main__':
    unittest.main()
"""

# Save file named 'test_MartinRuiz.py'
with open('test_MartinRuiz.ipynb', 'w') as f:
    f.write(test_code)
